version: '3.3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile_bot
    environment:
      TELEGRAM_BOT_TOKEN: "$TELEGRAM_BOT_TOKEN"
      DEVELOPER_CHAT_ID: "$DEVELOPER_CHAT_ID"
      TZ: Europe/Prague
      MONGO_USERNAME: "$MONGO_USERNAME"
      MONGO_PASSWORD: "$MONGO_PASSWORD"
    depends_on:
      - db
  db:
    container_name: db
    image: mongo
    restart: always
    ports:
      - '2002:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: "$MONGO_USERNAME"
      MONGO_INITDB_ROOT_PASSWORD: "$MONGO_PASSWORD"
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
