version: '3.3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile_bot
    environment:
      TELEGRAM_BOT_TOKEN: "$TELEGRAM_BOT_TOKEN"
      DEVELOPER_CHAT_ID: "$DEVELOPER_CHAT_ID"
      MONGO_USERNAME: "$MONGO_USERNAME"
      MONGO_PASSWORD: "$MONGO_PASSWORD"
      TZ: Europe/Prague
    depends_on:
      - db
  db:
    container_name: db
    image: mongo
    restart: always
    ports:
      - '2002:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: "$MONGO_USERNAME"
      MONGO_INITDB_ROOT_PASSWORD: "$MONGO_PASSWORD"
    volumes:
      - mongodb:/data/db
  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    environment:
      TZ: Europe/Prague
      command: uwsgi --ini /app/templates/uwsgi.ini
    depends_on:
      - db
    volumes:
      # - ./log/uwsgi:/var/log/uwsgi
      - ./socket:/app/socket
      - ./src/web/static/:/app/static:Z
  web:
    image: nginx:1.19-alpine
    volumes:
      #- ./log/nginx:/var/log/nginx
      - ./templates:/etc/nginx/templates
      - ./socket:/app/socket
      - ./src/web/static/:/app/static:Z
    ports:
      - "7778:7778"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=7778
    depends_on:
      - app
volumes:
  mongodb:
