FROM python:3.7-alpine
WORKDIR /app
RUN apk add --no-cache gcc musl-dev linux-headers tzdata
COPY . .
RUN pip install .
# XXX FIXME Figure out why the previous step doesn't install all dependencies
RUN pip install -r requirements.txt
RUN mkdir /var/log/uwsgi
ENTRYPOINT ["uwsgi", "--ini", "/app/templates/uwsgi.ini"]
