<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Czech Republic: information for refugees</title>

    <link rel="canonical" href="https://github.com/fernflower/showtelegramposts">

    <!-- Bootstrap core CSS -->
    <link href="/static/bootstrap-4.0.0/dist/css/bootstrap.min.css" rel="stylesheet">

  </head>

  <body>

    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">An autogenerated website to show categorized information from various telegram sources as one static webpage.</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Contact</h4>
              <ul class="list-unstyled">
                <li><a href="https://t.me/ahojky_chat" class="text-white">Telegram</a></li>
                <li><a href="https://github.com/fernflower/showtelegramposts">Github</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong>Czech Republic: information for refugees</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Чехия: информация для беженцев</h1>
          <p class="lead text-muted"></p>
          <p>
            <a href="/posts/documents" class="btn btn-secondary my-2">Документы</a>
            <a href="/posts/accommodation" class="btn btn-secondary my-2">Жилье</a>
            <a href="/posts/transport" class="btn btn-secondary my-2">Транспорт</a>
            <a href="/posts/help" class="btn btn-secondary my-2">Помощь</a>
            <a href="/posts/volunteers" class="btn btn-primary my-2">Волонтерам</a>
          </p>
          </p>
        </div>
      </section>

      {% block postsblock %}
      {% endblock postsblock %}

    </main>

    <footer class="text-muted">
      <div class="container">
        <p>All refugees will get Czech public health insurance, but 14.000 kids of long-term non-EU taxpayers still can't have it. You can help by signing <a href="https://www.petice.com/petice_za_vstup_dti_vech_pracujicich_v_r_do_systemu_zdravotniho_pojitni">this petition</a>.</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="/static/bootstrap-4.0.0/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="/static/bootstrap-4.0.0/assets/js/vendor/popper.min.js"></script>
    <script src="/static/bootstrap-4.0.0/dist/js/bootstrap.min.js"></script>
    <script src="/static/bootstrap-4.0.0/assets/js/vendor/holder.min.js"></script>
  </body>
</html>
